// insight.metalog.cppm — §8.1 wrapper module (1.5.0). GENERATED by gen_module_wrapper.py, hand-verified.
// Re-exports the package's global-module public surface; defs stay in src/*.cpp
// (.a byte-identical). 1.5.1 will unwrap this into a pure module.
module;
#include "insight/metalog/metalog_engine.hpp"

export module insight.metalog;

export namespace insight::metalog
{
using insight::metalog::FieldHistogram;
using insight::metalog::TopKEntry;
using insight::metalog::ReservoirEntry;
using insight::metalog::BranchingEntry;
using insight::metalog::TailSummary;
using insight::metalog::StatsBlock;
using insight::metalog::NGramEntry;
using insight::metalog::BehaviorBlock;
using insight::metalog::StabilityBlock;
using insight::metalog::WindowBlock;
using insight::metalog::ReportedWindowBounds;
using insight::metalog::ProducerBlock;
using insight::metalog::SourceBlock;
using insight::metalog::SourceRef;
using insight::metalog::EventTimeBounds;
using insight::metalog::ReDerivationCoordinate;
using insight::metalog::ProvenanceEntry;
using insight::metalog::MetaLogDocument;
using insight::metalog::TemplateEmissionMode;
using insight::metalog::MetaLogConfig;
using insight::metalog::TemplateDelta;
using insight::metalog::BranchingDelta;
using insight::metalog::NGramRateChange;
using insight::metalog::NGramDelta;
using insight::metalog::FieldHistogramDelta;
using insight::metalog::DocumentRef;
using insight::metalog::TailDelta;
using insight::metalog::MetaLogDiff;
using insight::metalog::MetaLogEngine;
using insight::metalog::to_json;
using insight::metalog::compose;
using insight::metalog::diff;
}
