name: Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: CodeRoasted/malf-toolchain/.github/workflows/coderoast-lint.yml@932d688f9bf39fa310b31f15643a2ee46af2df27
