name: Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: CodeRoasted/malf-toolchain/.github/workflows/coderoast-lint.yml@d0627449148015760e56caacd0aa1ea772e42af8
